"""
Django settings for ethiocoffee project.
Generated by Django 4.2.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------
# BASIC SETTINGS
# ----------------------------------

SECRET_KEY = 'django-insecure-i^k3eds+1t1(y)uc4i2ay)%6+ioqu4+m=%z5jajfdp5q086-x#'
DEBUG = True
ALLOWED_HOSTS = []


# ----------------------------------
# INSTALLED APPS
# ----------------------------------

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'coffeeapp',     # Your main web pages
]


# ----------------------------------
# MIDDLEWARE
# ----------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ethiocoffee.urls'


# ----------------------------------
# TEMPLATES
# ----------------------------------
# You keep your templates under: frontend/templates/
# Example: frontend/templates/base.html, products.html, etc.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'ethiocoffee.wsgi.application'


# ----------------------------------
# DATABASE
# ----------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ----------------------------------
# PASSWORD VALIDATION
# ----------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ----------------------------------
# INTERNATIONALIZATION
# ----------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Addis_Ababa'
USE_I18N = True
USE_TZ = True


# ----------------------------------
# STATIC FILES (CSS, JS, IMAGES)
# ----------------------------------

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'static',
]

# For production use:
# STATIC_ROOT = BASE_DIR / "staticfiles"


# ----------------------------------
# DEFAULT PRIMARY KEY
# ----------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
